# Generated by Django 4.0 on 2023-03-28 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petswebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='petswebsite.customuser'),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='temp_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='petswebsite.customuser'),
        ),
    ]
