# Generated by Django 4.0 on 2023-03-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petswebsite', '0002_adoption_owner_lostandfound_temp_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='image',
            field=models.ImageField(default='', upload_to='static/'),
        ),
    ]
