# Generated by Django 4.0 on 2023-03-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petswebsite', '0003_alter_adoption_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('life_expect', models.CharField(max_length=100)),
                ('coat_type', models.CharField(max_length=100)),
                ('coat_colors', models.CharField(max_length=100)),
                ('temperament', models.CharField(max_length=100)),
                ('alergies', models.CharField(max_length=100)),
            ],
        ),
    ]
