# Generated by Django 4.0 on 2023-03-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petswebsite', '0004_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='lorf',
            field=models.CharField(default='', max_length=10),
        ),
    ]
